x-copilot-litellm-params: &copilot_litellm_params
  extra_headers:
    editor-version: "vscode/1.95.0"
    editor-plugin-version: "copilot-chat/0.26.7"

general_settings:
  block_robots: true
  store_model_in_db: true

router_settings:
  num_retries: 3

litellm_settings:
  set_verbose: false
  cache: false
  drop_params: true

model_list:
  - model_name: github-copilot/gpt-5-mini
    model_info:
      mode: responses
    litellm_params:
      model: github_copilot/gpt-5-mini
      <<: *copilot_litellm_params

  - model_name: github-copilot/gpt-5.3-codex
    model_info:
      mode: responses
    litellm_params:
      model: github_copilot/gpt-5.3-codex
      <<: *copilot_litellm_params

  - model_name: github-copilot/claude-sonnet-4.6
    litellm_params:
      model: github_copilot/claude-sonnet-4.6
      <<: *copilot_litellm_params

  - model_name: github-copilot/gemini-3.1-pro-preview
    litellm_params:
      model: github_copilot/gemini-3.1-pro-preview
      <<: *copilot_litellm_params
